name: DevOps Pipeline

on:
  push:
    branches: [ main ]

  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: 20

    - name: Install Dependencies
      run: npm install

    - name: Run App Test
      run: |
        node app.js &
        sleep 5
        curl http://localhost:3000/health

    - name: Build Docker Image
      run: docker build -t devops-node-app .

    - name: Login DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Push Docker Image
      run: |
        docker tag devops-node-app ${{ secrets.DOCKER_USERNAME }}/devops-node-app:latest
        docker push ${{ secrets.DOCKER_USERNAME }}/devops-node-app:latest
